export const CREATE_ACTIVITY_ERROR = 'CREATE_ACTIVITY_ERROR';
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS';

export const DELETE_ACTIVITY_ERROR = 'DELETE_ACTIVITY_ERROR';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';

export const UPDATE_ACTIVITY_ERROR = 'UPDATE_ACTIVITY_ERROR';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
