export const CREATE_TRIP_ERROR = 'CREATE_TRIP_ERROR';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';

export const DELETE_TRIP_ERROR = 'DELETE_TRIP_ERROR';
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS';

export const UPDATE_TRIP_ERROR = 'UPDATE_TRIP_ERROR';
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS';
